gcc: make sure mingw build use mingw32-w64 configs
config/os/mingw32-w64 enables features that are disabled in
config/os/mingw32 due to old bugs that are fixed in w64.

Needed to build nativesdk-cmake for mingw:
error: 'to_wstring' is not a member of 'std'

Change-Id: I1823e8bc307403ce54137681cdec66c35109c473
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>