variscite.inc: BBMASK devil package
Since B2Qt release uses the same meta-variscite-imx
as Yocto, there was this devil bbapend recipe which
is only relevent for Yocto, resulting in an error
for B2Qt build:

ERROR: No recipes available for:
    meta-variscite-imx/recipes-graphics/devil/devil_%.bbappend

Add a BBMASK to ignore this recipe for B2Qt.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>