mingw: update meta-mingw layer and fix qtbase build
Thud branch is missing some of the fixes required for cmake, so use
sha1 from master branch. This needs a fix for for nativesdk-qtbase as
mingw64 headers have conflict depending on which order time.h and
pthread.h are included, causing error:
"qdatetime.cpp: error: 'localtime_r' was not declared in this scope"

Change-Id: Ie3faf69302594c1bead3bd0a5cc4bb2205c587ea
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>