Revert "meta-qt5: Update meta layer"
This reverts commit 6f79fa92a467d160c348a11bc24c340c72ac669d.

It broke qtbase build and therefore it blocks qtdeclarative in dev branch.
QtBase needs to be fixed before applying this.

 kernel/qnetworkinterface_linux.cpp: In instantiation of ‘void {anonymous}::ProcessNetlinkRequest<Lambda>::operator()(int, nlmsghdr*, char*, size_t, Lambda&&) [with Lambda = getInterfaces(int, char*)::<lambda(ifinfomsg*, size_t)>; size_t = unsigned int]’:
 kernel/qnetworkinterface_linux.cpp:216:36:   required from ‘void {anonymous}::processNetlinkRequest(int, nlmsghdr*, char*, size_t, Lambda&&) [with Lambda = getInterfaces(int, char*)::<lambda(ifinfomsg*, size_t)>; size_t = unsigned int]’
 kernel/qnetworkinterface_linux.cpp:319:6:   required from here
 kernel/qnetworkinterface_linux.cpp:161:48: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 kernel/qnetworkinterface_linux.cpp: In instantiation of ‘void {anonymous}::ProcessNetlinkRequest<Lambda>::operator()(int, nlmsghdr*, char*, size_t, Lambda&&) [with Lambda = getAddresses(int, char*, QList<QNetworkInterfacePrivate*>&)::<lambda(ifaddrmsg*, size_t)>; size_t = unsigned int]’:
 kernel/qnetworkinterface_linux.cpp:216:36:   required from ‘void {anonymous}::processNetlinkRequest(int, nlmsghdr*, char*, size_t, Lambda&&) [with Lambda = getAddresses(int, char*, QList<QNetworkInterfacePrivate*>&)::<lambda(ifaddrmsg*, size_t)>; size_t = unsigned int]’
 kernel/qnetworkinterface_linux.cpp:423:6:   required from here
 kernel/qnetworkinterface_linux.cpp:161:48: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 Makefile:26401: recipe for target '.obj/qnetworkinterface_linux.o' failed
 make[2]: *** [.obj/qnetworkinterface_linux.o] Error 1
 make[1]: *** [sub-network-make_first] Error 2
 make: *** [sub-src-make_first] Error 2

Change-Id: I51d13a67335c5aea8242f9f0f88bb8225dfce030
Reviewed-by: Jędrzej Nowacki <jedrzej.nowacki@qt.io>