qtbase: add workaround for mingw 7.0
QtBase now forces WINVER and friends to higher version than mingw 7.0
is able to support. Add workround to lower the NTDDI_VERSION to disable
TLS 1.3 support in schannel and fix compilation error:

src/plugins/tls/schannel/qtls_schannel.cpp:856:5: error: 'TLS_PARAMETERS' was not declared in this scope; did you mean 'VIDEOPARAMETERS'?
 |   856 |     TLS_PARAMETERS tlsParameters = {
 |       |     ^~~~~~~~~~~~~~

Change-Id: I8fb1ca951510c2441b8aef830a284416539fb65d
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit 0c1895aa5424b99edaf6bd49f5a4ad05551b0d24)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>